// generated by Neptune Namespaces v4.x.x
// file: S3Parallel/Lib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Lib'))
.addModules({
  Bisect:            require('./Bisect'),
  PromiseWorkerPool: require('./PromiseWorkerPool'),
  S3:                require('./S3'),
  S3Keys:            require('./S3Keys')
});