// generated by Neptune Namespaces v4.x.x
// file: S3P/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./S3P'))
.addModules({
  S3Tools: require('./S3Tools')
});
require('./Lib');