// generated by Neptune Namespaces v4.x.x
// file: S3P/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'S3P',
  (class S3P extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Lib/namespace');