// generated by Neptune Namespaces v4.x.x
// file: S3Parallel/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./S3Parallel'))
.addModules({
  S3P:            require('./S3P'),
  StandardImport: require('./StandardImport')
});
require('./Lib');