// generated by Neptune Namespaces v4.x.x
// file: S3Parallel/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./S3Parallel'))
.addModules({
  S3Comprehensions: require('./S3Comprehensions'),
  S3P:              require('./S3P'),
  S3PCli:           require('./S3PCli'),
  S3PCliCommands:   require('./S3PCliCommands'),
  StandardImport:   require('./StandardImport')
});
require('./Lib');