// generated by Neptune Namespaces v4.x.x
// file: S3Parallel/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'S3Parallel',
  (class S3Parallel extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Lib/namespace');