// generated by Neptune Namespaces v4.x.x
// file: test/index.js

(module.exports = require('./namespace'))

.addModules({
  S3ComprehensionsTest: require('./S3Comprehensions.test'),
  S3PTest:              require('./S3P.test'),
  S3PCli:               require('./S3PCli'),
  S3PCliTest:           require('./S3PCli.test'),
  StandardImport:       require('./StandardImport'),
  TestLib:              require('./TestLib')
});
require('./Lib');