// generated by Neptune Namespaces v4.x.x
// file: test/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Test',
  (class Test extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Lib/namespace');