// generated by Neptune Namespaces v4.x.x
// file: tests/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport: require('./StandardImport'),
  TestLib:        require('./TestLib')
});
require('./S3Parallel');