// generated by Neptune Namespaces v4.x.x
// file: tests/S3Parallel/Lib/index.js

(module.exports = require('./namespace'))

.addModules({
  PromiseWorkerPool: require('./PromiseWorkerPool'),
  S3Keys:            require('./S3Keys')
});