// generated by Neptune Namespaces v4.x.x
// file: tests/S3Parallel/Lib/namespace.js

module.exports = require('../namespace').addNamespace(
  'Lib',
  class Lib extends Neptune.PackageNamespace {}
);
