// generated by Neptune Namespaces v4.x.x
// file: tests/S3Parallel/namespace.js

module.exports = require('../namespace').addNamespace(
  'S3Parallel',
  class S3Parallel extends Neptune.PackageNamespace {}
);
require('./Lib/namespace');